baseURL: "https://exception.blog"
title: Jojo's Exception
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "Portuguese"
        weight: 1
        menu:
            main:
                # - name: Tags
                #   url: tags/
                #   weight: 10
                - name: About
                  url: about/
                  weight: 5

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Just another IT blog"
    author: Jojo
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: false
    displayFullLangName: false
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    homeInfoParams:
        Title: "`if (hope.Any()) return;`"
        Content: About 6a6f6a6f's life and job exceptions.
    socialIcons:
        - name: twitter
          url: "https://twitter.com/6a6f6a6f"
        - name: linkedin
          url: "https://www.linkedin.com/in/6a6f6a6f/"
        - name: github
          url: "https://github.com/6a6f6a6f"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true